sudo apt install ros-humble-gazebo-ros-pkgs
sudo apt install ros-humble-nav2-bringup
sudo apt install ros-humble-navigation2
sudo apt install ros-humble-turtlebot3*
sudo apt install ros-humble-nav2-simple-commander
sudo apt install ros-humble-slam-toolbox
sudo apt install ros-humble-xacro
sudo apt install ros-humble-joint-state-publisher-gui
sudo apt install ros-humble-ros2-control
sudo apt install ros-humble-ros2-controllers
sudo apt install ros-humble-gazebo-ros2-control 
sudo apt install ros-humble-robot-localization
sudo apt install ros-humble-rqt-robot-steering
sudo apt install python3-serial
sudo apt install ros-humble-rplidar-ros
sudo apt install ros-humble-image-transport-plugins
sudo apt install ros-humble-rqt-image-view
